[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "psij_ext"
version = "0.1"
description = 'PSI/J extension'
authors = [{ name = "K", email = "Notnow@notnow.com"}]